### ISSUE TITLE
"sophosInstall.sh" script: error message: WARNING: Secure coding is not enabled for restorable state!

### ISSUE THREAD

**Issue by sean-alex** [SecondSonConsulting/macOS-Scripts#6] opened 2024-06-05 15:38 UTC
Today, when running your "sophosInstall.sh" script from Terminal, the installation kicked out a "WARNING: Secure coding is not enabled for restorable state!" and I am wondering if anyone else has seen it (Not sure if the problem is a "me" thing, or something wider)?

The output:

```
2024-06-05 11:21:03 EDT  #---------------------------------------------------------------
2024-06-05 11:21:03 EDT  Finder process is found. Going to check if Dock is running.
2024-06-05 11:21:03 EDT  Dock process is found.
2024-06-05 11:21:03 EDT  Downloading installer to tmp folder...
2024-06-05 11:21:05 EDT  Verifying TeamIdentifier of Sophos Installer.app matches expected...
2024-06-05 11:21:05 EDT  Verification Passed.
2024-06-05 11:21:07 EDT  Start Sophos installation...
**2024-06-05 11:21:07.518 Sophos Installer[6656:82891] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.**
2024-06-05 11:21:19 EDT  Success
```

**Comment by BigMacAdmin** [comment] 2024-06-06 00:16
As mentioned on Slack, I am unable to reproduce this issue and suspect it may have to do with whatever wrapper script you're running (looks like a python error).

Closing this out, happy to discuss further on Slack.

**Closed as completed by BigMacAdmin** 2024-06-06 00:16 UTC
